# Generated by Django 5.1.15 on 2026-06-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("income", "Receita"), ("expense", "Despesa")],
                        default="income",
                        max_length=10,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("session", "Sessão"),
                            ("subscription", "Assinatura / Plano"),
                            ("material", "Material"),
                            ("refund", "Reembolso"),
                            ("other", "Outro"),
                        ],
                        default="session",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("pix", "PIX"),
                            ("credit_card", "Cartão de Crédito"),
                            ("debit_card", "Cartão de Débito"),
                            ("cash", "Dinheiro"),
                            ("bank_transfer", "Transferência Bancária"),
                            ("other", "Outro"),
                        ],
                        default="pix",
                        max_length=20,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Pago"),
                            ("pending", "Pendente"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=15,
                        verbose_name="Status do Pagamento",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Pago em"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Descrição / Observações"
                    ),
                ),
                (
                    "receipt_url",
                    models.URLField(
                        blank=True,
                        help_text="URL do PDF do recibo armazenado no Azure Blob Storage.",
                        verbose_name="URL do Recibo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_transactions",
                        to="agenda.appointment",
                        verbose_name="Consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação Financeira",
                "verbose_name_plural": "Transações Financeiras",
                "ordering": ["-created_at"],
            },
        ),
    ]
