# Generated by Django 5.1.15 on 2026-06-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("financeiro", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="financialtransaction",
            name="therapist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Terapeuta",
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["therapist", "payment_status"], name="fin_therapist_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialtransaction",
            index=models.Index(
                fields=["therapist", "created_at"], name="fin_therapist_created_idx"
            ),
        ),
    ]
