# Generated by Django 5.1.15 on 2026-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialtransaction",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("paid", "Pago"),
                    ("pending", "Pendente"),
                    ("cancelled", "Cancelado"),
                    ("refunded", "Estornado"),
                ],
                default="pending",
                max_length=15,
                verbose_name="Status do Pagamento",
            ),
        ),
    ]
