[pytest]
DJANGO_SETTINGS_MODULE = elo_terapeutico.settings.test
python_files = tests/*.py tests/**/*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    --strict-markers
    -v
    --tb=short
markers =
    slow: marca testes lentos (desative com -m 'not slow')
    integration: marca testes de integração
