# Generated by Django 5.1.15 on 2026-06-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="Início")),
                ("end_time", models.DateTimeField(verbose_name="Término")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Preenchido automaticamente a partir do horário de início/fim.",
                        verbose_name="Duração (min)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Agendada"),
                            ("confirmed", "Confirmada"),
                            ("missed", "Faltou"),
                            ("cancelled", "Cancelada"),
                            ("rescheduled", "Reagendada"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Observações visíveis para o terapeuta e secretária.",
                        verbose_name="Observações do agendamento",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(blank=True, verbose_name="Motivo do cancelamento"),
                ),
                (
                    "session_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor cobrado nesta consulta específica.",
                        max_digits=8,
                        verbose_name="Valor da sessão (R$)",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(
                        default=False, verbose_name="Consulta recorrente"
                    ),
                ),
                (
                    "recurrence_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WEEKLY", "Semanal"),
                            ("BIWEEKLY", "Quinzenal"),
                            ("MONTHLY", "Mensal"),
                        ],
                        help_text="Ex: WEEKLY (semanal), BIWEEKLY (quinzenal), MONTHLY (mensal).",
                        max_length=20,
                        verbose_name="Regra de recorrência",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "parent_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurrences",
                        to="agenda.appointment",
                        verbose_name="Consulta-pai (série recorrente)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-start_time"],
            },
        ),
    ]
