# Generated by Django 5.1.15 on 2026-06-23 00:00

import apps.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome completo"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("therapist", "Terapeuta"),
                            ("secretary", "Secretária"),
                            ("admin", "Administrador"),
                        ],
                        default="therapist",
                        max_length=20,
                        verbose_name="Papel no sistema",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Psicologia Cognitivo-Comportamental, Fonoaudiologia...",
                        max_length=100,
                        verbose_name="Especialidade",
                    ),
                ),
                (
                    "crp_number",
                    models.CharField(
                        blank=True,
                        help_text="Formato: XX/XXXXXX (ex: 06/123456)",
                        max_length=20,
                        validators=[apps.core.validators.validate_crp],
                        verbose_name="Número do CRP",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="Apresentação / Bio"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[apps.core.validators.validate_phone],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Foto de perfil",
                    ),
                ),
                (
                    "default_session_duration",
                    models.PositiveIntegerField(
                        default=50, verbose_name="Duração padrão da sessão (min)"
                    ),
                ),
                (
                    "default_session_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Valor padrão da sessão (R$)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de cadastro",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último login"
                    ),
                ),
                ("failed_login_attempts", models.PositiveSmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "Visualizou"),
                            ("CREATE", "Criou"),
                            ("UPDATE", "Atualizou"),
                            ("DELETE", "Deletou"),
                            ("EXPORT", "Exportou"),
                            ("ANONYMIZE", "Anonimizou"),
                        ],
                        max_length=20,
                        verbose_name="Ação",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Endereço IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data/Hora"
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="Descrição legível do objeto no momento do log.",
                        max_length=200,
                        verbose_name="Representação do objeto",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="users_audit_user_id_4b4ca5_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="users_audit_content_f4c6fb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="Dia da semana",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Início do atendimento")),
                ("end_time", models.TimeField(verbose_name="Fim do atendimento")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_hours",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Terapeuta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horário de Atendimento",
                "verbose_name_plural": "Horários de Atendimento",
                "ordering": ["weekday", "start_time"],
                "unique_together": {("therapist", "weekday")},
            },
        ),
    ]
