# Generated by Django 5.1.15 on 2026-07-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='AuditLog',
                ),
            ],
            database_operations=[],
        )
    ]
