# Generated by Django 5.2 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clinic_name",
            field=models.CharField(blank=True, max_length=160, verbose_name="Nome da clínica"),
        ),
        migrations.AddField(
            model_name="user",
            name="professional_address",
            field=models.JSONField(blank=True, default=dict, verbose_name="Endereço profissional"),
        ),
        migrations.AddField(
            model_name="user",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Termos aceitos em"),
        ),
        migrations.AddField(
            model_name="user",
            name="privacy_accepted_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Política de privacidade aceita em",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="trial_used_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name="Teste gratuito utilizado em",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Onboarding concluído em"),
        ),
    ]
