# Generated by Django 5.2 for revocable authentication sessions.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_account_lifecycle_and_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Identificador público",
                    ),
                ),
                (
                    "refresh_jti",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="JTI do refresh token",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Agente do dispositivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Criada em",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Última atividade",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True,
                        verbose_name="Expira em",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Revogada em",
                    ),
                ),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Motivo da revogação",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sessão autenticada",
                "verbose_name_plural": "Sessões autenticadas",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddIndex(
            model_name="authsession",
            index=models.Index(
                fields=["user", "revoked_at", "expires_at"],
                name="users_auths_user_active_idx",
            ),
        ),
    ]
