export const PUBLIC_FIELD_LABELS: Readonly<Record<string, string>> = {
  email: "E-mail",
  password: "Senha",
  password_confirm: "Confirmação da senha",
  current_password: "Senha atual",
  new_password: "Nova senha",
  full_name: "Nome",
  social_name: "Nome social",
  cpf: "CPF",
  phone: "Telefone",
  birth_date: "Data de nascimento",
  patient_id: "Paciente",
  therapist_id: "Terapeuta",
  body: "Mensagem",
  template_id: "Modelo",
  scheduled_at: "Agendamento",
  channel: "Canal",
  category: "Categoria",
  recipient_type: "Destinatário",
  provider: "Provedor",
  sender: "Remetente",
  sender_email: "E-mail do remetente",
  reply_to: "E-mail de resposta",
  non_field_errors: "Validação",
};
