# Generated by Django 5.1.15 on 2026-07-08 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='AuditLog',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('action', models.CharField(choices=[('VIEW', 'Visualizou'), ('CREATE', 'Criou'), ('UPDATE', 'Atualizou'), ('DELETE', 'Deletou'), ('EXPORT', 'Exportou'), ('ANONYMIZE', 'Anonimizou')], max_length=20, verbose_name='Ação')),
                        ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                        ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                        ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                        ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                        ('object_repr', models.CharField(blank=True, help_text='Descrição legível do objeto no momento do log.', max_length=200, verbose_name='Representação do objeto')),
                        ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                        ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                    ],
                    options={
                        'verbose_name': 'Log de Auditoria',
                        'verbose_name_plural': 'Logs de Auditoria',
                        'db_table': 'users_auditlog',
                        'ordering': ['-timestamp'],
                        'indexes': [models.Index(fields=['user', 'timestamp'], name='users_audit_user_id_4b4ca5_idx'), models.Index(fields=['content_type', 'object_id'], name='users_audit_content_f4c6fb_idx')],
                    },
                ),
            ],
            database_operations=[]
        )
    ]
