# Generated by Django 5.1.15 on 2026-06-23 00:00

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Nome completo"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        help_text="Somente dígitos (11 caracteres). Aceita formato com pontos/traços no input.",
                        max_length=11,
                        unique=True,
                        validators=[core.validators.validate_cpf],
                        verbose_name="CPF",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Data de nascimento")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Feminino"),
                            ("O", "Outro"),
                            ("N", "Prefiro não informar"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Gênero",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Formato: (11) 99999-9999",
                        max_length=20,
                        validators=[core.validators.validate_phone],
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "address",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Estrutura esperada: {"cep": "01310-100", "street": "Av. Paulista", "number": "1000", "complement": "Apto 42", "neighborhood": "Bela Vista", "city": "São Paulo", "state": "SP"}',
                        verbose_name="Endereço",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("inativo", "Inativo"),
                            ("alta", "Alta"),
                        ],
                        db_index=True,
                        default="ativo",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(
                        blank=True,
                        help_text="Como o paciente conheceu o terapeuta (ex: indicação, redes sociais, plano de saúde).",
                        max_length=255,
                        verbose_name="Origem / Indicação",
                    ),
                ),
                (
                    "guardian_name",
                    models.CharField(
                        blank=True,
                        help_text="Preencher para pacientes menores de 18 anos.",
                        max_length=255,
                        verbose_name="Nome do responsável",
                    ),
                ),
                (
                    "guardian_cpf",
                    models.CharField(
                        blank=True,
                        help_text="Somente dígitos. Preencher para pacientes menores de 18 anos.",
                        max_length=11,
                        validators=[core.validators.validate_cpf],
                        verbose_name="CPF do responsável",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Campo para anotações administrativas não clínicas. Informações clínicas devem ser registradas no Prontuário.",
                        verbose_name="Observações gerais",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcado via soft delete. Não edite manualmente.",
                        verbose_name="Ativo",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Preenchido automaticamente ao realizar soft delete.",
                        null=True,
                        verbose_name="Excluído em",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["full_name"],
            },
        ),
    ]
