# Generated by Django 5.1.15 on 2026-06-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"role": "therapist"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="patients",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Terapeuta responsável",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["therapist"], name="patient_therapist_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["cpf"], name="patient_cpf_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["status"], name="patient_status_idx"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["deleted_at"], name="patient_deleted_at_idx"),
        ),
    ]
