# Generated by Django 5.1.15 on 2026-06-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Ativo"),
                    ("inactive", "Inativo"),
                    ("discharged", "Alta"),
                ],
                db_index=True,
                default="active",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
