# Generated by Django 5.1.15 on 2026-06-23 00:00

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anamnesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_complaint",
                    core.fields.EncryptedTextField(
                        help_text="Motivo principal que levou o paciente a buscar terapia.",
                        verbose_name="Queixa principal",
                    ),
                ),
                (
                    "history",
                    core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Histórico de tratamentos anteriores, diagnósticos e intercorrências.",
                        verbose_name="Histórico clínico",
                    ),
                ),
                (
                    "medications",
                    core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Lista de medicamentos em uso no momento da avaliação inicial.",
                        verbose_name="Medicações em uso",
                    ),
                ),
                (
                    "family_history",
                    core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Doenças e transtornos relevantes na família do paciente.",
                        verbose_name="Histórico familiar",
                    ),
                ),
                (
                    "observations",
                    core.fields.EncryptedTextField(
                        blank=True,
                        help_text="Anotações adicionais não cobertas pelos campos anteriores.",
                        verbose_name="Observações gerais",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Anamnese",
                "verbose_name_plural": "Anamneses",
            },
        ),
        migrations.CreateModel(
            name="Evolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    core.fields.EncryptedTextField(
                        help_text="Texto descritivo da sessão terapêutica.",
                        verbose_name="Conteúdo da sessão",
                    ),
                ),
                (
                    "cid10",
                    models.CharField(
                        blank=True,
                        help_text="Código CID-10 associado à sessão (ex: F41.1).",
                        max_length=10,
                        verbose_name="CID-10",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(
                        help_text="Data em que a sessão terapêutica ocorreu.",
                        verbose_name="Data da sessão",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Evoluções bloqueadas não podem ser editadas. Só aceitam aditivos.",
                        verbose_name="Bloqueada",
                    ),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data/hora em que a evolução foi bloqueada.",
                        null=True,
                        verbose_name="Bloqueada em",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Evolução",
                "verbose_name_plural": "Evoluções",
                "ordering": ["-session_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvolutionAddendum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Justificativa clínica ou legal para o complemento.",
                        verbose_name="Motivo do aditivo",
                    ),
                ),
                (
                    "content",
                    core.fields.EncryptedTextField(
                        help_text="Texto do complemento à evolução original.",
                        verbose_name="Conteúdo do aditivo",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Aditivo de Evolução",
                "verbose_name_plural": "Aditivos de Evolução",
                "ordering": ["created_at"],
            },
        ),
    ]
