# Generated by Django 5.1.15 on 2026-06-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0003_initial"),
        ("patients", "0002_initial"),
        ("records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="anamnesis",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anamneses_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="anamnesis",
            name="patient",
            field=models.OneToOneField(
                help_text="Paciente ao qual esta anamnese pertence.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="anamnesis",
                to="patients.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="evolution",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                help_text="Consulta da agenda que originou esta evolução (opcional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evolution",
                to="agenda.appointment",
                verbose_name="Agendamento vinculado",
            ),
        ),
        migrations.AddField(
            model_name="evolution",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evolutions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="evolution",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="evolutions",
                to="patients.patient",
                verbose_name="Paciente",
            ),
        ),
        migrations.AddField(
            model_name="evolutionaddendum",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addenda_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Criado por",
            ),
        ),
        migrations.AddField(
            model_name="evolutionaddendum",
            name="evolution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="addenda",
                to="records.evolution",
                verbose_name="Evolução",
            ),
        ),
        migrations.AddIndex(
            model_name="evolution",
            index=models.Index(
                fields=["patient", "session_date"], name="evolution_patient_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evolution",
            index=models.Index(
                fields=["is_locked", "created_at"], name="evolution_lock_check_idx"
            ),
        ),
    ]
