# Generated by Django 5.1.15 on 2026-07-01 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_sync_patient_relationship_labels"),
        ("records", "0005_anamnesis_profile_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evolution",
            name="is_confidential",
            field=models.BooleanField(
                default=False,
                help_text="Marcar como confidencial. Informações visíveis apenas para o autor ou com permissão especial.",
                verbose_name="Confidencial",
            ),
        ),
        migrations.CreateModel(
            name="ClinicalExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(max_length=100, verbose_name="Tipo de exportação"),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="Nome do arquivo"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "period",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Período"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PROCESSING", "Processando"),
                            ("COMPLETED", "Concluído"),
                            ("FAILED", "Falhou"),
                            ("EXPIRED", "Expirado"),
                        ],
                        default="PENDING",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Tamanho (bytes)"
                    ),
                ),
                (
                    "download_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="URL de download"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Iniciado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finalizado em"
                    ),
                ),
                (
                    "next_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Próxima tentativa em"
                    ),
                ),
                (
                    "worker_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID do Worker"
                    ),
                ),
                ("retries", models.IntegerField(default=0, verbose_name="Tentativas")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Mensagem de erro"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clinical_exports_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_exports",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exportação Clínica",
                "verbose_name_plural": "Exportações Clínicas",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"], name="export_patient_status_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ClinicalFormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_name",
                    models.CharField(max_length=255, verbose_name="Nome do formulário"),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Categoria"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Enviado em"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Preenchido em"
                    ),
                ),
                (
                    "completed_by",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Preenchido por"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pendente"), ("completed", "Concluído")],
                        default="completed",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "answers_count",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade de respostas"
                    ),
                ),
                (
                    "form_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Snapshot do formulário"
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Respostas"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_responses",
                        to="patients.patient",
                        verbose_name="Paciente",
                    ),
                ),
                (
                    "therapist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="form_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Profissional responsável",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta de Formulário",
                "verbose_name_plural": "Respostas de Formulários",
                "ordering": ["-completed_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status"],
                        name="form_resp_patient_status_idx",
                    )
                ],
            },
        ),
    ]
