# Generated by Django 5.1.15 on 2026-07-01 21:33

import apps.records.treatment_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0006_evolution_is_confidential_clinicalexport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalexport",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.records.treatment_models.clinical_export_path,
                verbose_name="Arquivo gerado",
            ),
        ),
    ]
