# Generated by Django 5.1.15 on 2026-07-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0007_clinicalexport_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evolution",
            options={
                "ordering": ["-session_date", "-created_at"],
                "permissions": [
                    ("view_confidential_evolution", "Can view confidential evolution"),
                    (
                        "export_confidential_evolution",
                        "Can export confidential evolution",
                    ),
                ],
                "verbose_name": "Evolução",
                "verbose_name_plural": "Evoluções",
            },
        ),
    ]
