"""Compatibilidade para os services movidos para ``apps.scheduling``."""

from apps.scheduling.services import (
    apply_bulk_recurrence_change,
    build_appointments_csv,
    cancel_appointment_for_deletion,
    cancel_appointment_reminder,
    cancel_patient_package,
    create_appointment,
    create_appointment_resources,
    create_patient_package,
    create_schedule_block,
    end_recurrence,
    generate_recurrence_appointments,
    open_telemedicine_room,
    recurrence_dates,
    regenerate_telemedicine_links,
    release_package_session,
    remove_package_session,
    set_recurrence_status,
    sync_package_session_status,
    update_appointment,
    update_appointment_status,
)

__all__ = [
    "apply_bulk_recurrence_change",
    "build_appointments_csv",
    "cancel_appointment_for_deletion",
    "cancel_appointment_reminder",
    "cancel_patient_package",
    "create_appointment",
    "create_appointment_resources",
    "create_patient_package",
    "create_schedule_block",
    "end_recurrence",
    "generate_recurrence_appointments",
    "open_telemedicine_room",
    "recurrence_dates",
    "regenerate_telemedicine_links",
    "release_package_session",
    "remove_package_session",
    "set_recurrence_status",
    "sync_package_session_status",
    "update_appointment",
    "update_appointment_status",
]
