import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { communicationsService } from "./communications.service";
import type { CreateCommunicationPayload } from "./types";

export function useCommunicationDashboard(period: string) { return useQuery({ queryKey: ["communications-dashboard", period], queryFn: () => communicationsService.dashboard(period) }); }
export function useCommunications(filters?: Record<string, string | number | undefined>) { return useQuery({ queryKey: ["communications", filters], queryFn: () => communicationsService.list(filters) }); }
export function useCommunication(id: string | null) { return useQuery({ queryKey: ["communication", id], queryFn: () => communicationsService.detail(id!), enabled: Boolean(id) }); }
export function useCommunicationTemplates() { return useQuery({ queryKey: ["communication-templates"], queryFn: () => communicationsService.templates() }); }
export function useCommunicationAutomations() { return useQuery({ queryKey: ["communication-automations"], queryFn: communicationsService.automations }); }
export function useCommunicationChannels() { return useQuery({ queryKey: ["communication-channels"], queryFn: communicationsService.channels }); }
export function useCommunicationPatients() { return useQuery({ queryKey: ["communication-patients"], queryFn: communicationsService.patients }); }
export function useCreateCommunication() { const queryClient = useQueryClient(); return useMutation({ mutationFn: (payload: CreateCommunicationPayload) => communicationsService.create(payload), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["communications"] }); queryClient.invalidateQueries({ queryKey: ["communications-dashboard"] }); } }); }
export function useCommunicationAction() { const queryClient = useQueryClient(); return useMutation({ mutationFn: ({ id, action }: { id: string; action: "cancel" | "retry" | "send" | "mark-manually-sent" | "open-manual" }) => communicationsService.action(id, action), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["communications"] }); queryClient.invalidateQueries({ queryKey: ["communication"] }); queryClient.invalidateQueries({ queryKey: ["communications-dashboard"] }); } }); }
export function useToggleCommunicationAutomation() { const queryClient = useQueryClient(); return useMutation({ mutationFn: ({ id, active }: { id: number; active: boolean }) => communicationsService.toggleAutomation(id, active), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["communication-automations"] }) }); }
export function useNotifications(enabled = true) { return useQuery({ queryKey: ["communication-notifications"], queryFn: communicationsService.notifications, refetchInterval: enabled ? 60_000 : false, enabled }); }
export function useUnreadNotificationsCount() { return useQuery({ queryKey: ["communication-notifications-unread"], queryFn: communicationsService.unreadCount, refetchInterval: 60_000 }); }
export function useMarkNotificationRead() { const queryClient = useQueryClient(); return useMutation({ mutationFn: communicationsService.markNotificationRead, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["communication-notifications"] }); queryClient.invalidateQueries({ queryKey: ["communication-notifications-unread"] }); } }); }
export function useReadAllNotifications() { const queryClient = useQueryClient(); return useMutation({ mutationFn: communicationsService.readAllNotifications, onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["communication-notifications"] }); queryClient.invalidateQueries({ queryKey: ["communication-notifications-unread"] }); } }); }
