# Generated by Django 5.1.15 on 2026-06-23 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="therapist",
            field=models.ForeignKey(
                limit_choices_to={"role": "therapist"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Terapeuta",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["therapist", "start_time"], name="idx_appt_therapist_start"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "start_time"], name="idx_appt_patient_start"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="idx_appt_status"),
        ),
    ]
